check keywords.json on commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -50,6 +50,21 @@ check_ui_icon_name_consistency() {
   unset staged_files
 }
 
+check_ui_icon_keywords() {
+  staged_files="$(
+    git diff --cached --name-only --diff-filter=ACM | grep -E "^packages/ui-icons/docs/keywords\.json$" || true
+  )"
+
+  if [ -n "$staged_files" ]; then
+    npm --workspace=packages/ui-icons run util:check-keywords || {
+      echo "Error: Failed to validate UI icon keywords."
+      exit 1
+    }
+  fi
+
+  unset staged_files
+}
+
 update_t9n_manifest() {
   staged_files="$(
     git diff --cached --name-only --diff-filter=ACD | grep -E "packages/components/src/components/.*/assets/t9n/messages.json" || true
@@ -115,6 +130,7 @@ update_t9n_manifest
 update_internal_custom_prop_doc
 lint-staged
 check_ui_icon_name_consistency
+check_ui_icon_keywords
 update_stylelint_config_if_sass_file_edited
 
 exit 0
